# This is a basic workflow to help you get started with Actions

name: Test

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-test:
    environment: Actions
    env:
      MAVEN_PASS: ${{ secrets.TOKEN }}
      MAVEN_USER: ${{ secrets.USER }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: MAVEN_USER="${{ env.MAVEN_USER }}" MAVEN_PASS="${{ env.MAVEN_PASS }}" gradle build
      - run: gradle test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'